LoSimple/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('', include('home.urls')),
    path('booking/', include('booking.urls', namespace='booking')),
]

booking/urls.py
from django.urls import path
from .views import (
    book_hotel, hotel_list,
    check_date_overlap, my_books,
    book_edit, delete_book
    )

app_name = 'booking'

urlpatterns = [
    path('book/', hotel_list, name='hotel_list'),
    path('book/<int:hotel_id>/', book_hotel, name='book_hotel'),
    path('check_date_overlap/', check_date_overlap, name='check_date_overlap'),
    path('my_books/', my_books, name='my_books'),
    path('book/<int:book_id>', book_edit, name='book_edit'),
    path('delete_book/<int:book_id>', delete_book, name='delete_book'),
]

home/urls.py
from django.urls import path
from .views import home, about, images, contact_form, contact_success


urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('images/', images, name='images'),
    path('contact_form/', contact_form, name='contact_form'),
    path('contact_success/', contact_success, name='contact_success'),
]

booking/models.py
from django.db import models


class Hotel(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='media/hotel_images')
    price = models.FloatField(default=100)

    def __str__(self):
        return self.name


class Booking(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    check_in_date = models.DateField()
    check_out_date = models.DateField()

    def __str__(self):
        return f'{self.user.username} - {self.hotel.name}'

booking/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Hotel, Booking
from django.http import JsonResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required


def hotel_list(request):
    hotels = Hotel.objects.all().order_by('name')
    allhotels = []
    for hotel in hotels:
        allhotels.append({
            "name": hotel.name,
            "description": hotel.description,
            "image": hotel.image,
            "price": hotel.price,
            "id": hotel.id,

        })
    return render(request, 'book.html', {'hotels': hotels})


def my_books(request):
    my_books = Booking.objects.filter(user=request.user).all()
    allhotels = []
    for book in my_books:
        allhotels.append({
            "name": book.hotel.name,
            "description": book.hotel.description,
            "image": book.hotel.image,
            "price": book.hotel.price,
            "hotel_id": book.hotel.id,
            "book_id": book.id,

        })
    return render(request, 'my_books.html', {'hotels': allhotels})


def book_edit(request, book_id):
    book = Booking.objects.filter(id=book_id).first()
    if request.method == 'POST':
        book.check_in_date = request.POST.get('check_in_date')
        book.check_out_date = request.POST.get('check_out_date')
        book.save()
        return redirect('booking:book_edit', book_id=book.id)

    book_data = {
        "name": book.hotel.name,
        "description": book.hotel.description,
        "image": book.hotel.image,
        "price": book.hotel.price,
        "hotel_id": book.hotel.id,
        "book_id": book.id,
        "check_in_date": book.check_in_date,
        "check_out_date": book.check_out_date
    }

    return render(request, 'book_edit.html', {'book': book_data})


def delete_book(request, book_id):
    book = Booking.objects.filter(id=book_id).first()
    book.delete()
    return redirect('booking:my_books')


@login_required
def book_hotel(request, hotel_id):
    hotel = get_object_or_404(Hotel, id=hotel_id)
    check_in_date = request.POST.get('check_in_date')
    check_out_date = request.POST.get('check_out_date')

    if request.method == 'POST':
        user = request.user
        booking = Booking(hotel=hotel, user=user,
                          check_in_date=check_in_date,
                          check_out_date=check_out_date)
        booking.save()

        return render(request, 'success.html', {'hotel': hotel,
                                                'booking': booking})

    return render(request, 'booking.html', {'hotel': hotel})


def check_date_overlap(request):
    check_in_date = request.GET.get('check_in_date')
    check_out_date = request.GET.get('check_out_date')

    # Query the database to check for overlapping bookings
    overlapping_bookings = Booking.objects.filter(
        check_in_date__lt=check_out_date,
        check_out_date__gt=check_in_date,
        user=request.user,
    )

    overlap = overlapping_bookings.exists()

    return JsonResponse({'overlap': overlap})

booking/templates/book.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/book.css' %}">


{% for hotel in hotels %}


<div class="hotel-container">
    <div class="description-container">
        <div style="background-color:#FFDAB9; width: 655px; height: 400px;">
            <div style="height: 350px; align-items: center;">
                <br><br>


                <div class="hotel_name">
                    <p style="color: #973c54;"><strong>{{ hotel.name }}</strong></p>

                </div>

                <br>

                <div class="Hotel_Descrip">
                    <p style="color: #973c54;">
                        {{ hotel.description }}</p>

                </div>

            </div>

            <div style="height: 50px;">
                <a class="book-button" href="{% url 'booking:book_hotel' hotel.id %}">
                    BOOK HERE</a>
            </div>
        </div>
    </div>
    <div class="image-container">
        <div style="background-color: #FFDAB9; width: 468px; height: 400px;">
            <img style="width:100%; height:100%;" src="{{ hotel.image.url }}" alt="{{ hotel.name }}">
        </div>
    </div>
</div>

{% endfor %}

{% endblock %}

booking/templates/book_edit.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/edit_book.css' %}">
<div class="container">
    <div class="form-container">
        <h2>Edit Booking</h2>
        <form method="post">
            {% csrf_token %}
            <input type="hidden" name="book_id" value="{{ book.book_id }}">
            <div class="form-group">
                <label>Hotel Name: {{ book.name }}</label>
            </div>
            <div class="form-group">
                <label>Description: {{ book.description }}</label>
            </div>
            <div class="form-group">
                <img style="width:100%; height:100%;" src="{{ book.image.url }}" alt="OPS!">
            </div>
            <div class="form-group">
                <label>Price: {{ book.price }}</label>
            </div>

            <p id="message"></p>

            <div class="form-group">
                <label for="check_in_date">Check-in Date:</label>
                <input type="date" class="form-control" id="check_in_date" name="check_in_date"
                    value="{{ book.check_in_date|date:'Y-m-d' }}" onchange="check_date()">
            </div>
            <div class="form-group">
                <label for="check_out_date">Check-out Date:</label>
                <input type="date" class="form-control" id="check_out_date" name="check_out_date"
                    value="{{ book.check_out_date|date:'Y-m-d' }}" onchange="check_date()">
            </div>
            <button type="submit" id="savebtn" class="save-btn">Save Changes</button>
        </form>
    </div>
</div>


<script>
    function check_date() {
        var check_in_date = document.getElementById('check_in_date').value;
        var check_out_date = document.getElementById('check_out_date').value;
        if (!check_out_date) {
            check_out_date = check_in_date;
        }
        var startDate = new Date(check_in_date);
        var endDate = new Date(check_out_date);

        if (startDate > endDate) {

            document.getElementById('savebtn').disabled = true;
            document.getElementById('message').innerHTML = "Please select a correct date range!";
            document.getElementById('message').style.color = 'red';
            return;
        }

        $.ajax({
            url: '{% url "booking:check_date_overlap" %}',
            data: {
                'check_in_date': check_in_date,
                'check_out_date': check_out_date,
            },
            dataType: 'json',
            success: function (data) {
                if (data.overlap) {
                    // Dates overlap, disable the bookButton and display a message
                    document.getElementById('savebtn').disabled = true;
                    document.getElementById('message').innerHTML = "Dates Unavailable.";
                    document.getElementById('message').style.color = 'red';
                } else {
                    // Dates do not overlap, enable the bookButton and clear the message
                    document.getElementById('savebtn').disabled = false;
                    document.getElementById('message').innerHTML = "";
                }
            }
        });
    }


</script>

{% endblock %}

booking/templates/booking.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/book.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/modal.css' %}">


<h2>Book Hotel: {{ hotel.name }} </h2>
<h3 id="totalprice">Total = £{{ hotel.price}}</h3>
<h3 id="hotelprice" hidden>{{ hotel.price}}</h3>
<script>
    function calculate_total_price(totalvalue) {
        var check_in_date = document.getElementById('check_in_date').value;
        var check_out_date = document.getElementById('check_out_date').value;
        if (!check_out_date) {
            check_out_date = check_in_date;
        }
        var startDate = new Date(check_in_date);
        var endDate = new Date(check_out_date
        ); var currentDate = new Date();
        if (startDate > endDate || startDate > currentDate) {

            document.getElementById('bookButton').disabled = true;
            document.getElementById('message').innerHTML = "Please select a correct date range!";
            document.getElementById('message').style.color = 'red';
            return;
        }
        // Calculate the time difference in milliseconds
        var timeDiff = Math.abs(endDate.getTime() - startDate.getTime());

        // Calculate the number of days between the dates
        var diffDays = Math.ceil(timeDiff / (1000 * 3600 * 24));
        var hotelprice = document.getElementById('hotelprice').innerHTML;

        totalvalue.innerHTML = "Total = £" + (hotelprice * diffDays).toString();

        // Send AJAX request to check_date_overlap view
        $.ajax({
            url: '{% url "booking:check_date_overlap" %}',
            data: {
                'check_in_date': check_in_date,
                'check_out_date': check_out_date,
            },
            dataType: 'json',
            success: function (data) {
                if (data.overlap) {
                    // Dates overlap, disable the bookButton and display a message
                    document.getElementById('bookButton').disabled = true;
                    document.getElementById('message').innerHTML = "Dates Unavailable.";
                    document.getElementById('message').style.color = 'red';
                } else {
                    // Dates do not overlap, enable the bookButton and clear the message
                    document.getElementById('bookButton').disabled = false;
                    document.getElementById('message').innerHTML = "";
                }
            }
        });
    }


</script>
<p id="message"></p>
<form id="bookingForm" method="post">
    {% csrf_token %}
    <label for="check_in_date">Check-in Date:</label>
    <input type="date" id="check_in_date" name="check_in_date" required
        onchange="calculate_total_price(document.getElementById('totalprice'))">

    <label for="check_out_date">Check-out Date:</label>
    <input type="date" id="check_out_date" name="check_out_date" required
        onchange="calculate_total_price(document.getElementById('totalprice'))">

    <button id="bookButton" type="button">Book Now</button>
</form>

<!-- Modal -->
<div id="confirmModal" class="modal">
    <div class="modal-content">
        <h3>Confirmation</h3>
        <p>Are you sure you want to book?</p>
        <div class="modal-buttons">
            <button id="confirmButton">Confirm</button>
            <button id="cancelButton">Cancel</button>
        </div>
    </div>
</div>

<script src="{% static 'js/modal.js' %}"></script>
{% endblock %}

booking/templates/my_books.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/book.css' %}">


{% for hotel in hotels %}


<div class="hotel-container">
    <div class="description-container">
        <div style="background-color:#FFDAB9; width: 655px; height: 400px;">
            <div style="height: 350px; align-items: center;">
                <br><br>


                <div class="hotel_name">
                    <p style="color: #973c54;"><strong>{{ hotel.name }}</strong></p>

                </div>

                <br>

                <div class="Hotel_Descrip">
                    <p style="color: #973c54;">
                        {{ hotel.description }}</p>

                </div>

            </div>

            <div style="height: 50px;">
                <a class="book-button" href="{% url 'booking:book_edit' hotel.book_id %}">
                    EDIT</a>

                    <a class="book-button" style="background-color: red;" href="{% url 'booking:delete_book' hotel.book_id %}">
                        DELETE</a>
            </div>
        </div>
    </div>
    <div class="image-container">
        <div style="background-color: #FFDAB9; width: 468px; height: 400px;">
            <img style="width:100%; height:100%;" src="{{ hotel.image.url }}" alt="{{ hotel.name }}">
        </div>
    </div>
</div>

{% endfor %}

{% endblock %}

booking/templates/success.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h2>Booking Successful</h2>
<p>Your booking for {{ hotel.name }} has been confirmed.</p>
<p>Check-in Date: {{ booking.check_in_date }}</p>
<p>Check-out Date: {{ booking.check_out_date }}</p>
<a href="https://lo-simple-airbnb-17df7fdde095.herokuapp.com/">
    <button>Back to HomePage</button>
</a>
{% endblock %}