LoSimple/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('', include('home.urls')),
    path('booking/', include('booking.urls', namespace='booking')),
]

booking/urls.py
from django.urls import path
from .views import (
    book_hotel, hotel_list,
    check_date_overlap, my_books,
    book_edit, delete_book
    )

app_name = 'booking'

urlpatterns = [
    path('book/', hotel_list, name='hotel_list'),
    path('book/<int:hotel_id>/', book_hotel, name='book_hotel'),
    path('check_date_overlap/', check_date_overlap, name='check_date_overlap'),
    path('my_books/', my_books, name='my_books'),
    path('book/<int:book_id>', book_edit, name='book_edit'),
    path('delete_book/<int:book_id>', delete_book, name='delete_book'),
]

home/urls.py
from django.urls import path
from .views import home, about, images, contact_form, contact_success


urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('images/', images, name='images'),
    path('contact_form/', contact_form, name='contact_form'),
    path('contact_success/', contact_success, name='contact_success'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/43277a8bc2.js" crossorigin="anonymous"></script>
    <title>{% block title %}Lo Simple{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
</head>


<body>
    <div class="container">

        <nav>
            <ul>

                <li><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url 'booking:hotel_list' %}">Book</a></li>
                <li><a href="{% url 'about' %}">About</a></li>
                <li><a href="{% url 'images' %}">Images</a></li>
                <li><a href="{% url 'contact_form' %}">Contact</a></li>

                <li class="dropdown">
                    <a href="#">My Account</a>
                    <div class="dropdown-content">

                        {% if user.is_authenticated %}
                        <a href="{% url 'logout_view' %}">Logout</a>
                        <a href="{% url 'myprofile' %}">My Profile</a>
                        <a href="{% url 'booking:my_books' %}">My Bookings</a>
                        {% else %}
                        <a href="{% url 'register' %}">Sign Up</a>
                        <a href="{% url 'user_login' %}">Login</a>
                        {% endif %}



                    </div>
                </li>

                <!-- Add more navigation links as needed -->
            </ul>
        </nav>

        <h1 class="title"> LO SIMPLE</h1>
        <main>
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li class="message {{ message.tags }}" style="">
                    <span class="close-button" onclick="this.parentElement.style.display='none';">&times;</span>
                    {{ message }}
                </li>
                {% endfor %}
            </ul>
            {% endif %}
            {% block content %}
            <!-- The content of individual app pages will be inserted here -->
            {% endblock %}

            <footer>
                <div class="social-icons">
                    <a href="https://twitter.com/your-twitter-link"><i style="color:#973c54;"
                            class="fa-brands fa-twitter fa-xl">

                        </i></a>
                    <a href="https://www.instagram.com/your-instagram-link"><i
                            class="fa-brands fa-instagram fa-xl"></i></a>
                    <a href="https://www.facebook.com/your-facebook-link"><i style="color:#973c54;"
                            class="fa-brands fa-facebook fa-xl"></i></a>
                </div>
            </footer>


        </main>
    </div>

</body>

</html>